### PR TITLE
Fixed L0 Series info

### PR DESCRIPTION
**Pull request by staxhinho**
Fixed L0 Series image - was not showing.
Fixed L0 Series name - was 300 Series intead of L0 Series

### CODE REVIEW

**Comment by staxhinho** [comment]
@KeepinItRail You still alive bro?

**Comment by KeepinItRail** [comment]
Hey! Just about. Things have been crazy recently. 

Thanks for doing this. Definitely going to merge, though its going to be after I push a bunch of local changes through, so its all done cleanly.

**Comment by staxhinho** [comment]
And I'm also doing a portuguese translation of the mod

**Comment by KeepinItRail** [comment]
Thanks for this fix!

**Pull request merged**
